//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18047
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyHours.ServiceReferenceHappyHours {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="T_User", Namespace="http://schemas.datacontract.org/2004/07/HhDataLayer.DataAccess")]
    [System.SerializableAttribute()]
    public partial class T_User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HappyHours.ServiceReferenceHappyHours.T_Cocktail[] T_CocktailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HappyHours.ServiceReferenceHappyHours.T_Favorite[] T_FavoriteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int adminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HappyHours.ServiceReferenceHappyHours.T_Cocktail[] T_Cocktail {
            get {
                return this.T_CocktailField;
            }
            set {
                if ((object.ReferenceEquals(this.T_CocktailField, value) != true)) {
                    this.T_CocktailField = value;
                    this.RaisePropertyChanged("T_Cocktail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HappyHours.ServiceReferenceHappyHours.T_Favorite[] T_Favorite {
            get {
                return this.T_FavoriteField;
            }
            set {
                if ((object.ReferenceEquals(this.T_FavoriteField, value) != true)) {
                    this.T_FavoriteField = value;
                    this.RaisePropertyChanged("T_Favorite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int admin {
            get {
                return this.adminField;
            }
            set {
                if ((this.adminField.Equals(value) != true)) {
                    this.adminField = value;
                    this.RaisePropertyChanged("admin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="T_Cocktail", Namespace="http://schemas.datacontract.org/2004/07/HhDataLayer.DataAccess")]
    [System.SerializableAttribute()]
    public partial class T_Cocktail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HappyHours.ServiceReferenceHappyHours.T_CocktailsIngredients[] T_CocktailsIngredientsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HappyHours.ServiceReferenceHappyHours.T_Favorite[] T_FavoriteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HappyHours.ServiceReferenceHappyHours.T_User T_UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int difficultyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int durationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string picture_urlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string recipeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HappyHours.ServiceReferenceHappyHours.T_CocktailsIngredients[] T_CocktailsIngredients {
            get {
                return this.T_CocktailsIngredientsField;
            }
            set {
                if ((object.ReferenceEquals(this.T_CocktailsIngredientsField, value) != true)) {
                    this.T_CocktailsIngredientsField = value;
                    this.RaisePropertyChanged("T_CocktailsIngredients");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HappyHours.ServiceReferenceHappyHours.T_Favorite[] T_Favorite {
            get {
                return this.T_FavoriteField;
            }
            set {
                if ((object.ReferenceEquals(this.T_FavoriteField, value) != true)) {
                    this.T_FavoriteField = value;
                    this.RaisePropertyChanged("T_Favorite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HappyHours.ServiceReferenceHappyHours.T_User T_User {
            get {
                return this.T_UserField;
            }
            set {
                if ((object.ReferenceEquals(this.T_UserField, value) != true)) {
                    this.T_UserField = value;
                    this.RaisePropertyChanged("T_User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int difficulty {
            get {
                return this.difficultyField;
            }
            set {
                if ((this.difficultyField.Equals(value) != true)) {
                    this.difficultyField = value;
                    this.RaisePropertyChanged("difficulty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int duration {
            get {
                return this.durationField;
            }
            set {
                if ((this.durationField.Equals(value) != true)) {
                    this.durationField = value;
                    this.RaisePropertyChanged("duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string picture_url {
            get {
                return this.picture_urlField;
            }
            set {
                if ((object.ReferenceEquals(this.picture_urlField, value) != true)) {
                    this.picture_urlField = value;
                    this.RaisePropertyChanged("picture_url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string recipe {
            get {
                return this.recipeField;
            }
            set {
                if ((object.ReferenceEquals(this.recipeField, value) != true)) {
                    this.recipeField = value;
                    this.RaisePropertyChanged("recipe");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="T_Favorite", Namespace="http://schemas.datacontract.org/2004/07/HhDataLayer.DataAccess")]
    [System.SerializableAttribute()]
    public partial class T_Favorite : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HappyHours.ServiceReferenceHappyHours.T_Cocktail T_CocktailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HappyHours.ServiceReferenceHappyHours.T_User T_UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HappyHours.ServiceReferenceHappyHours.T_Cocktail T_Cocktail {
            get {
                return this.T_CocktailField;
            }
            set {
                if ((object.ReferenceEquals(this.T_CocktailField, value) != true)) {
                    this.T_CocktailField = value;
                    this.RaisePropertyChanged("T_Cocktail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HappyHours.ServiceReferenceHappyHours.T_User T_User {
            get {
                return this.T_UserField;
            }
            set {
                if ((object.ReferenceEquals(this.T_UserField, value) != true)) {
                    this.T_UserField = value;
                    this.RaisePropertyChanged("T_User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="T_CocktailsIngredients", Namespace="http://schemas.datacontract.org/2004/07/HhDataLayer.DataAccess")]
    [System.SerializableAttribute()]
    public partial class T_CocktailsIngredients : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HappyHours.ServiceReferenceHappyHours.T_Cocktail T_CocktailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HappyHours.ServiceReferenceHappyHours.T_Ingredient T_IngredientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HappyHours.ServiceReferenceHappyHours.T_Cocktail T_Cocktail {
            get {
                return this.T_CocktailField;
            }
            set {
                if ((object.ReferenceEquals(this.T_CocktailField, value) != true)) {
                    this.T_CocktailField = value;
                    this.RaisePropertyChanged("T_Cocktail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HappyHours.ServiceReferenceHappyHours.T_Ingredient T_Ingredient {
            get {
                return this.T_IngredientField;
            }
            set {
                if ((object.ReferenceEquals(this.T_IngredientField, value) != true)) {
                    this.T_IngredientField = value;
                    this.RaisePropertyChanged("T_Ingredient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="T_Ingredient", Namespace="http://schemas.datacontract.org/2004/07/HhDataLayer.DataAccess")]
    [System.SerializableAttribute()]
    public partial class T_Ingredient : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HappyHours.ServiceReferenceHappyHours.T_CocktailsIngredients[] T_CocktailsIngredientsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HappyHours.ServiceReferenceHappyHours.T_CocktailsIngredients[] T_CocktailsIngredients {
            get {
                return this.T_CocktailsIngredientsField;
            }
            set {
                if ((object.ReferenceEquals(this.T_CocktailsIngredientsField, value) != true)) {
                    this.T_CocktailsIngredientsField = value;
                    this.RaisePropertyChanged("T_CocktailsIngredients");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceHappyHours.IServiceClientHappyHours")]
    public interface IServiceClientHappyHours {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceClientHappyHours/DoWork", ReplyAction="http://tempuri.org/IServiceClientHappyHours/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceClientHappyHours/DoWork", ReplyAction="http://tempuri.org/IServiceClientHappyHours/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceClientHappyHours/GetListUser", ReplyAction="http://tempuri.org/IServiceClientHappyHours/GetListUserResponse")]
        HappyHours.ServiceReferenceHappyHours.T_User[] GetListUser(int max);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceClientHappyHours/GetListUser", ReplyAction="http://tempuri.org/IServiceClientHappyHours/GetListUserResponse")]
        System.Threading.Tasks.Task<HappyHours.ServiceReferenceHappyHours.T_User[]> GetListUserAsync(int max);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceClientHappyHoursChannel : HappyHours.ServiceReferenceHappyHours.IServiceClientHappyHours, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClientHappyHoursClient : System.ServiceModel.ClientBase<HappyHours.ServiceReferenceHappyHours.IServiceClientHappyHours>, HappyHours.ServiceReferenceHappyHours.IServiceClientHappyHours {
        
        public ServiceClientHappyHoursClient() {
        }
        
        public ServiceClientHappyHoursClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClientHappyHoursClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClientHappyHoursClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClientHappyHoursClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public HappyHours.ServiceReferenceHappyHours.T_User[] GetListUser(int max) {
            return base.Channel.GetListUser(max);
        }
        
        public System.Threading.Tasks.Task<HappyHours.ServiceReferenceHappyHours.T_User[]> GetListUserAsync(int max) {
            return base.Channel.GetListUserAsync(max);
        }
    }
}
