//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HhBackend.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HappyHoursEntities : DbContext
    {
        public HappyHoursEntities()
            : base("name=HappyHoursEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_Cocktail> T_Cocktail { get; set; }
        public DbSet<T_CocktailsIngredients> T_CocktailsIngredients { get; set; }
        public DbSet<T_Favorite> T_Favorite { get; set; }
        public DbSet<T_Ingredient> T_Ingredient { get; set; }
        public DbSet<T_User> T_User { get; set; }
    }
}
