//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HhBackend.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Favorite
    {
        public int id { get; set; }
        public int cocktail_id { get; set; }
        public int user_id { get; set; }
    
        public virtual T_Cocktail T_Cocktail { get; set; }
        public virtual T_User T_User { get; set; }
    }
}
