//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HhDataLayer.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyHappyHoursEntities : DbContext
    {
        public MyHappyHoursEntities()
            : base("name=MyHappyHoursEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_Cocktail> T_Cocktail { get; set; }
        public DbSet<T_CocktailsIngredients> T_CocktailsIngredients { get; set; }
        public DbSet<T_Favorite> T_Favorite { get; set; }
        public DbSet<T_Ingredient> T_Ingredient { get; set; }
        public DbSet<T_User> T_User { get; set; }
    }
}
