//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HhDataLayer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Cocktail
    {
        public T_Cocktail()
        {
            this.T_CocktailsIngredients = new HashSet<T_CocktailsIngredients>();
            this.T_Favorite = new HashSet<T_Favorite>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int difficulty { get; set; }
        public int duration { get; set; }
        public int creator_id { get; set; }
        public string description { get; set; }
        public string recipe { get; set; }
        public string picture_url { get; set; }
    
        public virtual T_User T_User { get; set; }
        public virtual ICollection<T_CocktailsIngredients> T_CocktailsIngredients { get; set; }
        public virtual ICollection<T_Favorite> T_Favorite { get; set; }
    }
}
