//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HhDataLayer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Ingredient
    {
        public T_Ingredient()
        {
            this.T_CocktailsIngredients = new HashSet<T_CocktailsIngredients>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<T_CocktailsIngredients> T_CocktailsIngredients { get; set; }
    }
}
