//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HhDataLayer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_User
    {
        public T_User()
        {
            this.T_Cocktail = new HashSet<T_Cocktail>();
            this.T_Favorite = new HashSet<T_Favorite>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public int admin { get; set; }
    
        public virtual ICollection<T_Cocktail> T_Cocktail { get; set; }
        public virtual ICollection<T_Favorite> T_Favorite { get; set; }
    }
}
